### ISSUE TITLE
some questions of function "generate_cloud_camera"

### ISSUE THREAD

**Issue by gaotihong** [ashafaei/ubc3v#1]
hello.
Recently, i am interested in  in the skeleton extraction.Thank you for your data.now i have some questions:
1.the code is follow:
init
instances = load_multicam('easy-pose', 'train', 150, 1:10);
target_init = 1;
instance = instances(target_init);
map_file = load('mapper.mat');
mapper = map_file.mapper;
[ cloud, labels, full_cloud, full_colors, mask ] = generate_cloud_camera( instance.Cam1, mapper );
2.the error is follow:
then have an error:
Undefined function 'rotz' for input arguments of type 'double'.

Error in generate_cloud_camera (line 57)
rot_mat =   rotz(0*camera.rotation(3)) ...
3.about error:
when i read the generate_cloud_camera.m, i found that rotz used  firstly is 

rot_mat =   rotz(0*camera.rotation(3)) ...
            * roty(rotyy) ...
            * rotx(rotyx);

4.i hope you will give me some advice;
thanks.

**Comment by ashafaei** [comment]
Hello @gaotihong ,

It seems like you're missing the rotz roty rotx functions.
Please see this issue here https://github.com/ashafaei/dense-depth-body-parts/issues/4

Let me know if you're still having issues.
