### ISSUE TITLE
16 double values for one joint

### ISSUE THREAD

**Issue by jiangwei221** [ashafaei/ubc3v#5]
Hi Shafaei:
I'm wondering what are the 16 values for one joint in the groundtruth file?

I read the matlab code and found only 13:15 in total 3 values are used.

By the way, the 13:15 GT joint location and the extrinsic camera parameters are in Maya world space coordinate, and point cloud from (depth_image * mapper) is in Kinect camera space, am I correct about it?

Thank you for your time!

**Comment by ashafaei** [comment]
Hello @jiangwei221,
The representation of posture is not just the XYZ. You could also characterize the rotation of the joint with a 3x3 rotation matrix. The 16 values are actually a flattened 4x4 matrix. If you reshape it to 4x4 you'll get a 3x3 rotation matrix on the left top corner, and a 3x1 offset vector on the right side (those are the 13:15 values).

```
   -4.8039   -1.1965   -8.6886  -11.1906
    1.5543    9.6336   -2.1860   45.5783
    8.6317   -2.4006   -4.4419  -23.3961
         0         0         0    1.0000
```
This representation of joint is more informative than the mere xyz values, but it's rarely inferred in computer vision applications.

Yes, you are right. The joint locations are in the Maya space, whereas, the reconstruction is in the Kinect space. You need to use the extrinsic camera parameters (in the groundtruth file for each camera) to properly rotate and translate the point cloud to merge them. This is also implemented in the code [process/generate_cloud_camera.m](https://github.com/ashafaei/ubc3v/blob/master/process/generate_cloud_camera.m).

**Comment by jiangwei221** [comment]
Thank you for the reply! I understand now!
