### ISSUE TITLE
Cannot access the datasets

### ISSUE THREAD

**Issue by danasko** [ashafaei/ubc3v#6]
Hi, I'm struggling to download the datasets with Error 403 Access denied. Is that denied intentionally ?

**Comment by ashafaei** [comment]
Hi,

Thank you for bringing this to my attention. I will look into it and let you know what’s going on. The files are hosted on university servers, they may have made changes that have broken the links. I’ll get back you on this.

**Comment by danasko** [comment]
Great, thanks.

**Comment by ashafaei** [comment]
It looks like someone has taken the liberty to remove all my data from the department servers. The links should be back online.
